services:
  tg-bot:
    env_file:
      - app/.env.secure
    build:
      context: ../
      dockerfile: deploy/app/Dockerfile
    volumes:
      - ../:/app
    networks:
      - outsider

networks:
  outsider:
    external: true